version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: pgdatabase
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
    ports:
      - "5432:5432"
    volumes:
      - ./infra/databases/sql/data/db:/var/lib/postgresql/data
    restart: always

  app:
    build:
#      context: ../
#      dockerfile: deployment/Dockerfile
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "5000:5000"
      - "5678:5678" # Debug
    depends_on:
      - db
